[project]
name = "worker"
version = "0.1.0"
description = "AI Ticketing worker scaffold"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["worker"]
