[project]
name = "api"
version = "0.1.0"
description = "AI Ticketing API service scaffold"
dependencies = [
  "fastapi==0.111.0",
  "uvicorn[standard]==0.30.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["app"]
